### ISSUE TITLE
Merge exercises into handouts

### ISSUE THREAD

**Issue by lazyfrosch** [NETWAYS/fundamentals4puppet-training#21]
Is there a reason we have exercises in handouts and additional paper?

We could merge this together and handout the material + solutions.

@mwaldmueller ?

**Comment by mwaldmueller** [comment]
With separate exercises you have the possibility to add more text, but as far as I see it's not really used for detailed descriptions.
Would appreciate it if we remove the exercises.

**Comment by dnsmichi** [comment]
Can we put this on the agenda for the guild meeting? This affects all trainings.

**Comment by lbetz** [comment]
It's already on the list....

**Comment by lbetz** [comment]
refs #32

**Comment by martialblog** [comment]
Project will be archived for now. Closing issues for now.
