### ISSUE TITLE
Incorporate PDK

### ISSUE THREAD

**Issue by dgoetz** [NETWAYS/fundamentals4puppet-training#39]
[PDK (Puppet Development Kit)](https://puppet.com/docs/pdk/1.x/pdk.html) is the new tool to generate Puppet modules, classes and tasks from templates according the styleguide and should be mentioned.

**Comment by dgoetz** [comment]
After giving the training this week I have an idea for incorporating it. I would mention it when talking about the structure as a tool that helps you to create the structure and go into details at the end of the module chapter with an exercise to migrate the self-written module to pdk. Many users will face exactly this challenge at work when migrating or maintaining modules.

**Comment by martialblog** [comment]
Project will be archived for now. Closing issues for now.
