### ISSUE TITLE
Puppet 3 removal

### ISSUE THREAD

**Issue by dgoetz** [NETWAYS/fundamentals4puppet-training#43]
I would not remove Puppet 3 until Puppet 5/6 is widely accepted, but it is out of support for quite a while, so planning is not wrong.

* Remove from Repositories slides
* Remove or reduce inheritance as there is no styleguide conform usage anymore (this would also remove params.pp and so require more changes for example in the hiera chapter)

**Comment by martialblog** [comment]
Project will be archived for now. Closing issues for now.
